[2024-09-17T22:30:53.227+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/321.py
[2024-09-17T22:30:53.228+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/321.py for tasks to queue
[2024-09-17T22:30:53.229+0000] {logging_mixin.py:149} INFO - [2024-09-17T22:30:53.229+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/321.py
[2024-09-17T22:30:53.289+0000] {logging_mixin.py:149} INFO - [2024-09-17T22:30:53.284+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/321.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/321.py", line 26, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-09-17T22:30:53.290+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/321.py
[2024-09-17T22:30:53.314+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/321.py took 0.090 seconds
[2024-09-17T22:31:23.449+0000] {processor.py:157} INFO - Started process (PID=60) to work on /opt/airflow/dags/321.py
[2024-09-17T22:31:23.452+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/321.py for tasks to queue
[2024-09-17T22:31:23.454+0000] {logging_mixin.py:149} INFO - [2024-09-17T22:31:23.454+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/321.py
[2024-09-17T22:31:23.568+0000] {logging_mixin.py:149} INFO - [2024-09-17T22:31:23.562+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/321.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/321.py", line 26, in <module>
    task1 = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-09-17T22:31:23.570+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/321.py
[2024-09-17T22:31:23.598+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/321.py took 0.155 seconds
