[2024-11-01T20:44:16.701+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_binance_dag1.draw_smth_graphs manual__2024-11-01T20:28:48.572787+00:00 [queued]>
[2024-11-01T20:44:16.715+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_binance_dag1.draw_smth_graphs manual__2024-11-01T20:28:48.572787+00:00 [queued]>
[2024-11-01T20:44:16.716+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2024-11-01T20:44:16.738+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): draw_smth_graphs> on 2024-11-01 20:28:48.572787+00:00
[2024-11-01T20:44:16.748+0000] {standard_task_runner.py:57} INFO - Started process 356 to run task
[2024-11-01T20:44:16.751+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_binance_dag1', 'draw_smth_graphs', 'manual__2024-11-01T20:28:48.572787+00:00', '--job-id', '833', '--raw', '--subdir', 'DAGS_FOLDER/binance.Dag1.py', '--cfg-path', '/tmp/tmpq4mm8reb']
[2024-11-01T20:44:16.754+0000] {standard_task_runner.py:85} INFO - Job 833: Subtask draw_smth_graphs
[2024-11-01T20:44:16.771+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-11-01T20:44:16.813+0000] {task_command.py:410} INFO - Running <TaskInstance: api_binance_dag1.draw_smth_graphs manual__2024-11-01T20:28:48.572787+00:00 [running]> on host 3e776c2a96a1
[2024-11-01T20:44:16.928+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Danil' AIRFLOW_CTX_DAG_ID='api_binance_dag1' AIRFLOW_CTX_TASK_ID='draw_smth_graphs' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T20:28:48.572787+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-01T20:28:48.572787+00:00'
[2024-11-01T20:44:16.979+0000] {logging_mixin.py:149} INFO -    Имя монеты Дата открытия  Цена последней совершенной сделки
0         SOL    2024-10-23                           170.8500
1         SOL    2024-10-24                           177.1900
2         SOL    2024-10-25                           164.9000
3         SOL    2024-10-26                           170.8800
4         SOL    2024-10-27                           176.6300
5         SOL    2024-10-28                           178.2900
6         SOL    2024-10-29                           179.4200
7         SOL    2024-10-30                           174.8700
8         SOL    2024-10-31                           168.6900
9         SOL    2024-11-01                           164.0600
10      1INCH    2024-10-23                             0.2646
11      1INCH    2024-10-24                             0.2743
12      1INCH    2024-10-25                             0.2479
13      1INCH    2024-10-26                             0.2510
14      1INCH    2024-10-27                             0.2573
15      1INCH    2024-10-28                             0.2592
16      1INCH    2024-10-29                             0.2641
17      1INCH    2024-10-30                             0.2598
18      1INCH    2024-10-31                             0.2460
19      1INCH    2024-11-01                             0.2398
20        SUI    2024-10-23                             1.9775
21        SUI    2024-10-24                             1.9369
22        SUI    2024-10-25                             1.7520
23        SUI    2024-10-26                             1.7950
24        SUI    2024-10-27                             1.7559
25        SUI    2024-10-28                             1.7729
26        SUI    2024-10-29                             2.0731
27        SUI    2024-10-30                             2.0828
28        SUI    2024-10-31                             1.9715
29        SUI    2024-11-01                             1.9761
30        TON    2024-10-23                             5.1400
31        TON    2024-10-24                             5.1280
32        TON    2024-10-25                             4.7760
33        TON    2024-10-26                             4.9250
34        TON    2024-10-27                             4.9970
35        TON    2024-10-28                             5.0170
36        TON    2024-10-29                             5.0200
37        TON    2024-10-30                             4.9890
38        TON    2024-10-31                             4.8460
39        TON    2024-11-01                             4.8610
40       STRK    2024-10-23                             0.3997
41       STRK    2024-10-24                             0.4014
42       STRK    2024-10-25                             0.3599
43       STRK    2024-10-26                             0.3703
44       STRK    2024-10-27                             0.3786
45       STRK    2024-10-28                             0.3767
46       STRK    2024-10-29                             0.3942
47       STRK    2024-10-30                             0.3923
48       STRK    2024-10-31                             0.3710
49       STRK    2024-11-01                             0.3620
[2024-11-01T20:44:17.206+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/binance.Dag1.py", line 92, in draw_graphs
    plt.savefig(f'C:/Airflow/imagines/grafik{name}.png')  # Указываем полный путь и имя файла
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 977, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/figure.py", line 3058, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2325, in print_figure
    **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 543, in print_png
    dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/image.py", line 1675, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/PIL/Image.py", line 2429, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Airflow/imagines/grafik1INCH.png'
[2024-11-01T20:44:17.240+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=api_binance_dag1, task_id=draw_smth_graphs, execution_date=20241101T202848, start_date=20241101T204416, end_date=20241101T204417
[2024-11-01T20:44:17.259+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 833 for task draw_smth_graphs ([Errno 2] No such file or directory: 'C:/Airflow/imagines/grafik1INCH.png'; 356)
[2024-11-01T20:44:17.290+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-11-01T20:44:17.322+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
